# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b6a4eb4e70e4768311c971fd30d5498ab5d708775a0c0eb8242dc072b8e3faeebf03f23189f42fc0a632f78c191a4cfa5bd3b51db578a7515b0440826d203bef

test:
  secret_key_base: 5bca833b2223659fee3dd6ce14b82c179af245c93ca55a4020d2a2c739823e378d6d8c29f44c40da8355c41c91aa546771b10c7b721464b232f9d9eea0d35064

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
